### ISSUE TITLE
Editable mode

### ISSUE THREAD

**Issue by TeamSPoon** [niftythoughts/ansi-highlighter-premium#1]
Does this plugin let you edit ANSI files inline or does it imply files are read-only ?

**Comment by niftythoughts** [comment]
The plugin opens log files in ANSI Highlighter mode by default (read-only), but it does also support a plain mode that allows inline edits, see section **'Double Display Mode'** [here](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium) for details.

As of the current version (22.1.3) your edits may take time before they get reflected into ANSI Highlighter view, the next version (coming soon) will include a refresh button.
