### ISSUE TITLE
Allow parsing files when using Big Data Tools JetBrains plugin

### ISSUE THREAD

**Issue by kpervin** [niftythoughts/ansi-highlighter-premium#11]
Currently ANSI Highlighter works with the Remote Host deployment tool, but not the Remote File Systems/Big Data Tools plugin that is officially supplied by Jetbrains. While it is a downloaded plugin, it is not a paid plugin and it would be nice to have compatibility.

**Comment by niftythoughts** [comment]
Pending JB Approval, thanks for reporting.
<img width="506" alt="Screen Shot 2023-12-10 at 10 31 03 PM" src="https://github.com/niftythoughts/ansi-highlighter-premium/assets/104358007/0757f36e-45b0-4fad-afb3-e7353b99f20c">

**Comment by niftythoughts** [comment]
Resolved with [23.3.0](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium/versions/stable/452433?noRedirect=true)
