### ISSUE TITLE
ANSI Highlighter Premium plugin is not compatible with IntelliJ IDEA 2023.3

### ISSUE THREAD

**Issue by simonallaway-abra** [niftythoughts/ansi-highlighter-premium#12]
The plugin page says:
`Not compatible with the version of your running IDE (IntelliJ IDEA 2023.3)`

From the 'about' dialog:
```
IntelliJ IDEA 2023.3 (Ultimate Edition)
Build #IU-233.11799.241, built on December 1, 2023
Licensed to Simon Allaway
Subscription is active until December 13, 2023.
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
  CheckStyle-IDEA (5.85.0)
  com.intellij.aqua (233.11799.259)
  org.intellij.scala (2023.3.17)
  org.jetbrains.plugins.docker.gateway (233.11799.244)
Kotlin: 233.11799.241-IJ
```

**Comment by niftythoughts** [comment]
Pending JB approval, thanks for reporting.
<img width="506" alt="Screen Shot 2023-12-10 at 10 31 03 PM" src="https://github.com/niftythoughts/ansi-highlighter-premium/assets/104358007/289b3315-0a7f-4077-8c98-14fc6eef4d38">

**Comment by niftythoughts** [comment]
Resolved with [23.3.0](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium/versions/stable/452433?noRedirect=true)

**Comment by simonallaway-abra** [comment]
Thanks for the swift resolution!

**Comment by simonallaway-abra** [comment]
They approved and it's installed
![image](https://github.com/niftythoughts/ansi-highlighter-premium/assets/105663178/1b355c3f-15b3-454d-84cf-30d3cf7c4607)
