### ISSUE TITLE
Incompatible with 2022.2

### ISSUE THREAD

**Issue by ethitter** [niftythoughts/ansi-highlighter-premium#2]
Is there an estimate for when this will be updated for the newest IntelliJ release?

**Comment by niftythoughts** [comment]
New release will be submitted Monday, August 1st - approval takes less than 48 hours.

Thanks for reporting.

**Comment by niftythoughts** [comment]
Submitted today August 3rd, approval is pending - apologies for the 2-day delay.

**Comment by niftythoughts** [comment]
Release [22.2.1](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium/versions/stable/204613) available for download.
