### ISSUE TITLE
Ansi Highlighter plugin breaks the functionality of the plugin Elasticsearch

### ISSUE THREAD

**Issue by an2riy** [niftythoughts/ansi-highlighter-premium#3]
It seems that  **Ansi Highlighter** breaks the functionality of the Elasticsearch https://github.com/AntonShuvaev/elasticsearch4idea/issues/83#issuecomment-1214303604

**Comment by niftythoughts** [comment]
The last update of AHP pre-processes the first 250 rows of opened files to auto-detect ANSI codes and suggest to render them, if detected, regardless their extension.

Feature traced in the change log (see [plugin home page](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium)) - meant to address poor user experience described [here](https://stackoverflow.com/questions/70913901/display-ansi-colours-in-text-file-in-pycharm#answer-72486152).

A fix would be to restrict pre-processing to plain text files. 

Should be submitted in the next 24 hours - approval takes no longer than 48 hours (usually less)

**Comment by niftythoughts** [comment]
Fix available for download in versions [2.2.3](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium/versions/stable/209122) and [2.1.5](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium/versions/stable/209121) depending on user IDE version.

Thanks for reporting

**Comment by an2riy** [comment]
Confirm that it was fixed. 
Thanks
